-- ============================================================
-- VYNTRO Gaming Store — Product Catalog Seed (PKR)
-- Run this in your Supabase SQL Editor if you ever need to re-seed or migrate
-- ============================================================

insert into public.products (
  name,
  slug,
  category,
  cost_price,
  selling_price,
  discount_percentage,
  stock_quantity,
  collections,
  images,
  description,
  material_specs,
  warranty_period,
  delivery_time,
  care_instructions,
  is_active
) values
-- MICE
(
  'Razer DeathAdder V3',
  'razer-deathadder-v3',
  'Mice',
  13999,
  19499,
  0,
  45,
  array['fps', 'best-sellers', 'wired'],
  array['/Gaming Mouse 🎮🖱️.jpg', '/mouse_cat.jpg'],
  'Ergonomic wired esports mouse engineered for top-tier competitive FPS performance. Features ultra-lightweight 59g chassis, Focus Pro 30K optical sensor, true 8000Hz polling rate, and gen-3 optical switches rated for 90 million clicks.',
  '59g ergonomic shell, Razer Focus Pro 30K Optical Sensor, True 8000Hz polling rate, Gen-3 Optical Switches (90M clicks), Speedflex cable',
  '1 Year',
  '2–4 business days',
  'Keep dry. Clean optical sensor with compressed air. Wipe shell with a clean microfiber cloth.',
  true
),
(
  'Razer Viper V3 Pro',
  'razer-viper-v3-pro',
  'Mice',
  32000,
  44499,
  5,
  30,
  array['fps', 'wireless', 'pro-gear', 'hot-picks', 'claw', 'fingertip'],
  array['/Razer Viper V3 Pro Sentinels Edition Review _ Ultra-Light 54g Wireless Gaming Mouse.jpg', '/Gaming Mouse 🎮🖱️.jpg'],
  'The definitive wireless esports weapon. Symmetrical 54g ultra-lightweight shape, Focus Pro 35K Gen-2 Optical Sensor, up to 8000Hz wireless polling via HyperPolling dongle, and up to 95 hours of competitive battery life.',
  '54g symmetrical chassis, Razer Focus Pro 35K Optical Sensor Gen-2, 8000Hz HyperPolling wireless, up to 95h battery life, 100% PTFE mouse feet',
  '2 Years',
  '2–4 business days',
  'Recharge using supplied USB-C Speedflex cable. Clean mouse skates with isopropyl wipe.',
  true
),
(
  'Logitech G Pro X Superlight 2',
  'logitech-g-pro-x-superlight-2',
  'Mice',
  32000,
  44499,
  0,
  38,
  array['fps', 'wireless', 'minimalistic', 'best-sellers', 'claw', 'palm'],
  array['/Gaming Mouse 🎮🖱️.jpg', '/mouse_cat.jpg'],
  'The champion mouse of international esports. Upgraded with LIGHTFORCE hybrid optical-mechanical switches, HERO 2 32K sensor, 2000Hz/4000Hz wireless polling, and up to 95 hours of marathon battery life at just 60g.',
  '60g minimalist chassis, HERO 2 32K Sensor (500+ IPS), LIGHTFORCE Hybrid Optical-Mechanical Switches, LIGHTSPEED wireless, USB-C charging',
  '2 Years',
  '2–4 business days',
  'Keep dry. Store dongle securely when traveling. Clean shell with dry microfiber cloth.',
  true
),
(
  'Razer Basilisk V3 Pro',
  'razer-basilisk-v3-pro',
  'Mice',
  32000,
  44499,
  0,
  22,
  array['mmo', 'wireless', 'rgb', 'palm'],
  array['/Gaming Mouse 🎮🖱️.jpg'],
  'Advanced ergonomic gaming mouse featuring the revolutionary Razer HyperScroll Tilt Wheel with free-spin and tactile modes, 11 programmable buttons, 13-zone Chroma RGB lighting with full underglow, and Focus Pro 30K sensor.',
  '112g ergonomic right-handed shell, HyperScroll Tilt Wheel, Focus Pro 30K Optical Sensor, 11 programmable buttons, 13-zone Razer Chroma RGB',
  '2 Years',
  '2–4 business days',
  'Use soft brush to remove dust around scroll wheel. Wipe grip zones with mild damp cloth.',
  true
),
(
  'Logitech G502 X Plus',
  'logitech-g502-x-plus',
  'Mice',
  32000,
  44499,
  0,
  40,
  array['mmo', 'wireless', 'rgb', 'best-sellers', 'palm'],
  array['/Gaming Mouse 🎮🖱️.jpg'],
  'The latest evolution of the world’s most popular gaming mouse. Redesigned with LIGHTFORCE hybrid switches, LIGHTSYNC 8-LED dynamic RGB lighting, HERO 25K sub-micron sensor, and reversible/removable DPI-shift button.',
  '106g ergonomic design, LIGHTFORCE optical-mechanical switches, HERO 25K Sensor, LIGHTSYNC 8-LED active RGB, LIGHTSPEED wireless + POWERPLAY compatible',
  '2 Years',
  '2–4 business days',
  'Wipe shell with microfiber cloth. Keep charging contacts clean.',
  true
),

-- KEYBOARDS
(
  'Wooting 60HE',
  'wooting-60he',
  'Keyboards',
  35000,
  48999,
  0,
  15,
  array['benchmark', 'imported', 'minimalistic', 'rapid-trigger', '60%'],
  array['/keyboard_cat.jpg'],
  'The undisputed benchmark for competitive gaming keyboards. 60% compact layout powered by Lekker Hall Effect magnetic switches. Features true Rapid Trigger technology with 0.1mm to 4.0mm customizable analog actuation per key.',
  '60% compact layout, Gateron x Lekker Magnetic Hall Effect switches, Rapid Trigger (0.1–4.0mm actuation), hot-swappable switch sockets, PBT keycaps',
  '2 Years',
  '2–4 business days',
  'Calibrate via Wootility web software. Clean with keycap puller and compressed air.',
  true
),
(
  'Razer Huntsman V3 Pro TKL',
  'razer-huntsman-v3-pro-tkl',
  'Keyboards',
  46000,
  63999,
  5,
  20,
  array['fps', 'analog', 'pro-gear', 'hot-picks', '80%'],
  array['/keyboard_cat.jpg'],
  'Tenkeyless analog optical gaming keyboard engineered for pro-level tactical shooters. Gen-2 Analog Optical Switches with Rapid Trigger mode, quick onboard actuation adjustment with LED array indicator, and textured doubleshot PBT keycaps.',
  'Tenkeyless (TKL 80%) layout, Razer Analog Optical Gen-2 Switches, Rapid Trigger 0.1–4.0mm, textured doubleshot PBT keycaps, brushed 5052 aluminum top plate, magnetic leatherette wrist rest',
  '2 Years',
  '2–4 business days',
  'Detach magnetic wrist rest before moving. Clean keycaps with damp cloth.',
  true
),
(
  'SteelSeries Apex Pro TKL',
  'steelseries-apex-pro-tkl',
  'Keyboards',
  44000,
  61499,
  0,
  25,
  array['fps', 'analog', 'best-sellers', '80%'],
  array['/keyboard_cat.jpg'],
  'World’s fastest keyboard featuring OmniPoint 2.0 adjustable hyper-magnetic switches with Rapid Trigger. Integrated OLED Smart Display delivers direct settings info, Discord alerts, and game stats at a glance.',
  'TKL 80% form factor, OmniPoint 2.0 Adjustable Magnetic Switches (0.2–3.8mm), OLED Smart Display, Series 5000 aircraft-grade aluminum frame, per-key dynamic RGB',
  '2 Years',
  '2–4 business days',
  'Keep OLED screen clean with dry microfiber cloth. Do not use chemical solvents.',
  true
),
(
  'Logitech G Pro X TKL',
  'logitech-g-pro-x-tkl',
  'Keyboards',
  40000,
  55999,
  0,
  28,
  array['fps', 'wireless', 'pro-gear', '80%'],
  array['/keyboard_cat.jpg'],
  'Engineered with and for tournament champions. LIGHTSPEED wireless technology with pro-grade GX mechanical switches, dual-shot PBT keycaps, customizable LIGHTSYNC RGB, and dedicated game mode switch in a compact travel-ready design.',
  'TKL 80% competitive design, Hot-swappable GX mechanical switches, LIGHTSPEED wireless + Bluetooth + USB-C wired, dual-shot PBT keycaps, hard-shell travel case included',
  '2 Years',
  '2–4 business days',
  'Store in included hardshell carrying case during transit. Clean dust using compressed air.',
  true
),
(
  'Corsair K70 RGB Pro',
  'corsair-k70-rgb-pro',
  'Keyboards',
  34000,
  47499,
  0,
  32,
  array['rgb', 'best-sellers', '100%'],
  array['/keyboard_cat.jpg'],
  'Iconic full-size mechanical keyboard equipped with authentic Cherry MX switches, durable brushed aluminum frame, AXON 8,000Hz hyper-processing, tournament mode lock switch, and precision-molded PBT double-shot keycaps.',
  'Full-size 104-key layout, Genuine Cherry MX switches, Corsair AXON 8000Hz hyper-polling, precision PBT double-shot keycaps, aluminum top plate, dedicated volume roller',
  '2 Years',
  '2–4 business days',
  'Disconnect USB cable prior to cleaning. Wipe aluminum top plate with microfiber cloth.',
  true
),

-- IEMS
(
  'SIMGOT EM6L',
  'simgot-em6l',
  'IEMs',
  12000,
  16999,
  0,
  50,
  array['budget-friendly', 'hybrid-driver', 'hot-picks', 'hybrid'],
  array['/IEMs_cat.jpg'],
  'High-precision hybrid in-ear monitors equipped with 1 Dynamic Driver and 4 Balanced Armatures per ear. Tuned to the H-2019 target curve for exceptional 3D directional positioning in tactical shooters like CS2 and Valorant.',
  '1DD + 4BA hybrid 5-driver acoustic system, high-precision 3D-printed resin cavity, CNC aluminum alloy faceplate, detachable silver-plated OFC 2-pin 0.78mm cable',
  '1 Year',
  '2–4 business days',
  'Clean nozzle earwax filters with included brush. Store in dry pouch away from moisture.',
  true
),
(
  'Truthear ZERO: RED',
  'truthear-zero-red',
  'IEMs',
  11000,
  15499,
  0,
  42,
  array['budget-friendly', 'dual-dynamic', 'best-sellers', 'dynamic'],
  array['/IEMs_cat.jpg'],
  'Collaboratively tuned with Crinacle. Features dual polyurethane suspension composite liquid crystal dome dynamic drivers (10mm woofer + 7.8mm tweeter) delivering crystal-clear footsteps and punchy sub-bass without masking mid-frequencies.',
  'Dual dynamic drivers (10mm + 7.8mm LCP), medical-grade 3D DLP resin shell, 0.78mm 2-pin detachable cable, 10-ohm bass impedance adapter included',
  '1 Year',
  '2–4 business days',
  'Keep drivers dry. Regularly swap or clean silicone tips with warm water (detached from IEMs).',
  true
),
(
  'Final Audio VR3000',
  'final-audio-vr3000',
  'IEMs',
  10000,
  13999,
  0,
  35,
  array['gaming', 'low-latency', 'fps', 'dynamic'],
  array['/IEMs_cat.jpg'],
  'Engineered in Japan specifically for spatial audio in gaming and VR. Features Final’s f-Core DU dynamic driver with ultra-accurate spatial acoustic localization that pinpoints audio distance and vertical elevation flawlessly.',
  '6mm high-precision f-Core DU dynamic driver, lightweight ABS ergonomic housing (20g), oxygen-free copper cable with inline controller & microphone, Final Type-E ear tips',
  '1 Year',
  '2–4 business days',
  'Handle cable gently at strain reliefs. Store in protective pouch when not in use.',
  true
),
(
  'Moondrop Aria 2',
  'moondrop-aria-2',
  'IEMs',
  16000,
  22499,
  0,
  44,
  array['audiophile', 'minimalistic', 'hot-picks', 'dynamic'],
  array['/IEMs_cat.jpg'],
  'Next-generation single dynamic driver IEM featuring a newly developed TiN ceramic-coated spherical dome composite diaphragm. Delivers ultra-low distortion, wide soundstage, and immaculate vocal presence with screw-in swappable audio plugs.',
  'TiN ceramic-coated dynamic driver, alloy casting CNC-milled shell with brass acoustic nozzle, modular cable with 3.5mm & 4.4mm balanced plugs',
  '1 Year',
  '2–4 business days',
  'Unscrew modular plugs gently when swapping. Clean brass nozzle mesh periodically.',
  true
),
(
  '7Hz Salnotes Zero 2',
  '7hz-salnotes-zero-2',
  'IEMs',
  4200,
  5999,
  0,
  60,
  array['budget-friendly', 'entry-level', 'best-sellers', 'dynamic'],
  array['/IEMs_cat.jpg'],
  'The undisputed king of budget gaming IEMs. Upgraded 10mm dynamic driver with flexible PU+LCP diaphragm providing enhanced low-frequency punch and accurate positional audio cues without treble harshness.',
  '10mm composite PU+LCP dynamic driver, stainless steel faceplate with ergonomic resin body, high-purity silver-plated OFC detachable 0.78mm 2-pin cable',
  '1 Year',
  '2–4 business days',
  'Avoid pulling directly on cable wires; hold the 2-pin housing when detaching.',
  true
),

-- ACCESSORIES
(
  'SteelSeries QcK Heavy',
  'steelseries-qck-heavy',
  'Accessories',
  7000,
  9999,
  0,
  55,
  array['mousepad', 'cloth', 'best-sellers'],
  array['/Zindoo XXL Gaming Mouse Mat 900 x 400 mm.jpg', '/tactical-mousepad.jpg'],
  'The heavyweight legend used by esports pros worldwide. Features an extra thick 6mm non-slip rubber base that eliminates uneven desk surfaces, micro-woven cloth surface optimized for both low and high DPI mouse tracking, and durable stitched perimeter.',
  '900×300×6mm (XL), legendary QcK micro-woven cloth surface, extra thick 6mm natural rubber non-slip base, wash-resistant',
  '1 Year',
  '2–4 business days',
  'Hand wash gently with lukewarm water and mild dish soap. Air dry flat. Do not machine dry.',
  true
),
(
  'ZOWIE G-SR III',
  'zowie-g-sr-iii',
  'Accessories',
  11000,
  15499,
  0,
  30,
  array['mousepad', 'cloth', 'pro-gear', 'hot-picks'],
  array['/tactical-mousepad.jpg', '/Zindoo XXL Gaming Mouse Mat 900 x 400 mm.jpg'],
  'The gold standard esports control surface for tactical FPS titles like CS2 and Valorant. Newly upgraded uniform high-density rubber base with moisture-resistant micro-texture cloth provides consistent stopping power and smooth glide.',
  '490×420×3.5mm, specialized high-density flat rubber base, humidity-resistant tight cloth weave, anti-fray stitched edge',
  '1 Year',
  '2–4 business days',
  'Wipe surface with microfiber cloth. Keep away from direct sunlight.',
  true
),
(
  'Logitech G640',
  'logitech-g640',
  'Accessories',
  6000,
  8499,
  0,
  40,
  array['mousepad', 'cloth', 'minimalistic'],
  array['/sakura-mousepad.jpg', '/red_mousepad.jpg'],
  'Large cloth gaming mousepad featuring moderate surface friction ideal for low-DPI flick maneuvers in competitive shooters. Clean consistent surface texture matched specifically to Logitech G sensors.',
  '460×400×3mm, heat-treated moderate friction cloth weave, flexible non-slip natural rubber base, rolled-edge packaging',
  '1 Year',
  '2–4 business days',
  'Clean surface gently with damp cloth. Do not bend backwards.',
  true
),
(
  'Razer Gigantus V2',
  'razer-gigantus-v2',
  'Accessories',
  5000,
  6999,
  0,
  48,
  array['mousepad', 'cloth', 'best-sellers'],
  array['/red_mousepad.jpg', '/sakura-mousepad.jpg'],
  'Soft gaming mouse mat with textured micro-weave cloth surface for fluid swipes and pixel-precise aim. High-density thick rubber foam with non-slip base ensures the pad stays anchored during intense firefights.',
  'Available in L/XXL, textured micro-weave cloth, 3mm thick high-density rubber foam base, anti-slip grooved rubber bottom',
  '1 Year',
  '2–4 business days',
  'Wipe clean with a damp cloth. Avoid harsh abrasive cleaners.',
  true
),
(
  'Razer Strider',
  'razer-strider',
  'Accessories',
  8000,
  11499,
  0,
  25,
  array['mousepad', 'hybrid', 'hot-picks'],
  array['/dragon-wave-mousepad.jpg', '/tactical-mousepad.jpg'],
  'Hybrid mouse mat that combines the frictionless speed of a hard surface with the rollable portability and comfort of a soft mat. Engineered with a water-resistant warp-proof surface and reinforced anti-fray stitched borders.',
  '450×400×3mm, hybrid polyester hard/soft weave surface, water-resistant hydrophobic coating, grooved anti-slip rubber base, seamless stitched edges',
  '1 Year',
  '2–4 business days',
  'Water-resistant surface: wipe spills instantly with dry towel. Rinse with cool water if needed.',
  true
)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  cost_price = excluded.cost_price,
  selling_price = excluded.selling_price,
  discount_percentage = excluded.discount_percentage,
  stock_quantity = excluded.stock_quantity,
  collections = excluded.collections,
  images = excluded.images,
  description = excluded.description,
  material_specs = excluded.material_specs,
  warranty_period = excluded.warranty_period,
  delivery_time = excluded.delivery_time,
  care_instructions = excluded.care_instructions,
  is_active = excluded.is_active,
  updated_at = now();
