-- ============================================================
-- VYNTRO Gaming Store — 10 Custom Themed Mousepads Seed (PKR)
-- Run this in your Supabase SQL Editor if needed
-- ============================================================

insert into public.products (
  name,
  slug,
  category,
  cost_price,
  selling_price,
  discount_percentage,
  stock_quantity,
  collections,
  images,
  description,
  material_specs,
  warranty_period,
  delivery_time,
  care_instructions,
  is_active
) values
-- 1. MINIMALISTIC (2)
(
  'Monochrome Topo Stealth Deskmat',
  'monochrome-topo-stealth-deskmat',
  'XXL Deskmats',
  450,
  800,
  0,
  50,
  array['minimalistic', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'control'],
  array['/maybe_notext.jpeg', '/tactical-mousepad.jpg'],
  'Sleek monochromatic topographic contour elevation line-art tailored for pristine, distraction-free setups. Premium micro-textured poly-weave surface provides effortless mouse tracking with consistent stopping power.',
  'High-density natural rubber base, anti-fray precision stitched edges, water-resistant coating. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe clean with a damp microfiber cloth. Air dry flat. Do not machine wash.',
  true
),
(
  'Nordic Slate Minimalist Mat',
  'nordic-slate-minimalist-mat',
  'XXL Deskmats',
  450,
  800,
  0,
  45,
  array['minimalistic', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'best-sellers'],
  array['/sakura-mousepad.jpg', '/maybe.jpeg'],
  'Subtle architectural grid lines and clean Scandinavian aesthetics. Built for high-productivity workspaces and aesthetic gaming desk setups.',
  'Ultra-dense micro-weave cloth, anti-slip herringbone backing, 4mm plush thickness. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe clean with a damp microfiber cloth. Air dry flat. Do not machine wash.',
  true
),

-- 2. FPS TACTICAL (2)
(
  'Redline Tactical Strike Mat',
  'redline-tactical-strike-mat',
  'XXL Deskmats',
  450,
  800,
  0,
  60,
  array['fps', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'speed', 'hot-picks'],
  array['/red_mousepad.jpg', '/mousepad-hd.png'],
  'Calibrated specifically for tournament tactical shooters. Low dynamic friction delivers lightning-fast crosshair flicks with consistent stopping power for pinpoint micro-adjustments in CS2 and Valorant.',
  'Frictionless speed weave, military-grade reinforced border stitching, 4mm natural rubber base. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Clean with damp cloth. Keep away from direct excessive heat.',
  true
),
(
  'Ghost Recon Precision FPS Deskmat',
  'ghost-recon-precision-fps-deskmat',
  'XXL Deskmats',
  450,
  800,
  0,
  40,
  array['fps', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'control', 'best-sellers'],
  array['/tactical-mousepad.jpg', '/Zindoo XXL Gaming Mouse Mat 900 x 400 mm.jpg'],
  'Tactical HUD geometric telemetry pattern with high stopping power. Engineered for low-DPI arm aimers who demand absolute control in high-stakes competitive clutch rounds.',
  'Textured control fabric, 4mm zero-slip rubber grip, heat-treated anti-fray edge. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe surface with microfiber cloth. Air dry completely.',
  true
),

-- 3. ABSTRACT AND WAVES (2)
(
  'Great Kanagawa Dark Wave Deskmat',
  'great-kanagawa-dark-wave-deskmat',
  'XXL Deskmats',
  450,
  800,
  0,
  55,
  array['abstract', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'speed', 'best-sellers'],
  array['/dragon-wave-mousepad.jpg', '/Wave MTG gaming mat, dragon 350x600x2mm mouse pad MTG MTG DTCG CCG RPG, collection card, soft rubber.jpg'],
  'An intense modern reimagining of the iconic Japanese great wave with deep indigo and storm froth aesthetics. High-speed multi-directional glide optimized for optical sensors.',
  'High-definition thermal sublimation print (fade-proof), ultra-smooth surface, non-slip textured rubber base. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Hand wash gently with cool water and mild soap. Air dry flat.',
  true
),
(
  'Neon Fluid Abyssal Waves Mat',
  'neon-fluid-abyssal-waves-mat',
  'XXL Deskmats',
  450,
  800,
  0,
  35,
  array['abstract', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'speed'],
  array['/mousepad-trimmed.png', '/dragon-wave-mousepad.jpg'],
  'Mesmerizing psychedelic liquid marble flow with fluid neon currents. High-speed glide surface that makes every mouse swipe feel smooth and effortless.',
  'Silky smooth poly-blend fabric, water-repellent surface finish, reinforced low-profile stitching. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe spills instantly with dry towel. Rinse with cool water if needed.',
  true
),

-- 4. FANTASY AND MYTHIC (2)
(
  'Dragon Sovereign Mythic Battlemat',
  'dragon-sovereign-mythic-battlemat',
  'XXL Deskmats',
  450,
  800,
  0,
  45,
  array['fantasy', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'hot-picks'],
  array['/Wave MTG gaming mat, dragon 350x600x2mm mouse pad MTG MTG DTCG CCG RPG, collection card, soft rubber.jpg', '/dragon-wave-mousepad.jpg'],
  'Summon the elder storm dragon across your battlestation. Mythic fantasy artwork rendered in rich chromatic depth with extreme detail and vibrant contrast.',
  'Premium textured cloth weave, 4mm cushioned rubber core, 360-degree precision anti-fray stitching. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Clean with damp cloth. Air dry flat away from sunlight.',
  true
),
(
  'Celestial Phoenix Rebirth Deskmat',
  'celestial-phoenix-rebirth-deskmat',
  'XXL Deskmats',
  450,
  800,
  0,
  50,
  array['fantasy', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'best-sellers'],
  array['/Sakura Landscape Mousepad Mountain Pink White Mouse Pad Rubber Bottom Game Pad Office accessories.jpg', '/red_mousepad.jpg'],
  'Ascend with the mythical golden firebird spreading wings across celestial constellations. Balanced glide engineered for both tracking and rapid flick maneuvers.',
  'Optical sensor-tuned micro-texture, spill-resistant nano coating, heavy natural rubber base. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe spills immediately. Air dry flat.',
  true
),

-- 5. ANIME AND MANGA (2)
(
  'Domain Curse Anime Deskmat',
  'domain-curse-anime-deskmat',
  'XXL Deskmats',
  450,
  800,
  0,
  50,
  array['anime', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'hot-picks', 'best-sellers'],
  array['/jjk_mousepad.jpg'],
  'Unleash malevolent cursed energy with high-contrast manga screentone art. Crisp deep inks and striking red accents create an unforgettable battle station centerpiece.',
  'Ultra-dense woven microfiber, anti-curling rubber bottom, seamless edge stitching. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe clean with a damp cloth. Do not machine wash.',
  true
),
(
  'Sakura Blossom Neo-Tokyo Manga Mat',
  'sakura-blossom-neo-tokyo-manga-mat',
  'XXL Deskmats',
  450,
  800,
  0,
  40,
  array['anime', 'non-rgb', 'basic', 'large', 'xl', 'xxl', 'xxxl', 'control'],
  array['/Sakura Landscape Mousepad Mountain Pink White Mouse Pad Rubber Bottom Game Pad Office accessories.jpg', '/sakura-mousepad.jpg'],
  'Serene cherry blossom mountain sanctuary blended with retro cyberpunk anime aesthetics. Ultra-soft touch cloth for comfortable marathon gaming sessions.',
  'Comfort cloth surface, 4mm wrist-friendly cushioning, anti-skid rubber base, anti-fray hemmed edge. __SIZES__{"Basic":800,"Large":1200,"XL":1500,"XXL":2000,"XXXL":3200}__SIZES__',
  '6 Months',
  '2–4 business days',
  'Wipe gently with damp cloth and mild soap. Air dry completely.',
  true
)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  cost_price = excluded.cost_price,
  selling_price = excluded.selling_price,
  discount_percentage = excluded.discount_percentage,
  stock_quantity = excluded.stock_quantity,
  collections = excluded.collections,
  images = excluded.images,
  description = excluded.description,
  material_specs = excluded.material_specs,
  warranty_period = excluded.warranty_period,
  delivery_time = excluded.delivery_time,
  care_instructions = excluded.care_instructions,
  is_active = excluded.is_active,
  updated_at = now();
